# default_language_version:
#  python: python3.9
default_stages: [ commit ]
files: '^(.*\.(py|sh|md|ya?ml))$'
fail_fast: false
minimum_pre_commit_version: '0'
repos:
  # Meta and Local
  - repo: meta
    hooks:
      - id: check-useless-excludes
        name: Check useless excludes
      - id: identity
        name: Identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        types: [ file ]
        args: [ '--maxkb=100' ]
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-yaml
        name: Check yaml
      - id: check-json
        name: Check json
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-symlinks
        name: Check for symlinks
      - id: check-toml
        name: Check toml
      - id: end-of-file-fixer
        name: End of file fixer
      - id: trailing-whitespace
        name: Trailing whitespace remover
      - id: debug-statements
        name: Check for pdb and ipdb
      - id: detect-aws-credentials
        name: Detect AWS credentials
        args: [ --allow-missing-credentials ]
      - id: detect-private-key
        name: Detect private key

  # Python
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.2
    hooks:
      - id: autopep8
        name: Autopep8
  - repo: https://github.com/myint/autoflake
    rev: 'v2.0.0'
    hooks:
      - id: autoflake
        name: autoflake
        args: [ '--in-place', '--remove-all-unused-imports' ]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.201'
    hooks:
      - id: ruff
        name: Ruff
        args: [ "--fix" ]

  # Security issues
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        name: Bandit
        args: [ "-r" , "-c", "pyproject.toml" ]
        additional_dependencies: [ "bandit[toml]" ]

  #  Dockerfile
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint

  # Pipeline
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
        name: Check GitHub workflows
        files: ^(.github/workflows/.*\.yml)$

  # EditorConfig
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.6.1
    hooks:
      - id: editorconfig-checker
        language: python
