name: Publish Package to Pypi
on:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: fregante/setup-git-user@v1
      # Setup .npmrc file to publish to npm
      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Publish package to PyPI
        with:
          package-dir: dist/
          verbose: true # to debug if twine upload fails
          print-hash: true
          password: ${{ secrets.PYPI_API_TOKEN }}


